apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  postgres-username: postgres
  postgres-password: mysecretpassword
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  AUTH_SERVICE_URL: "http://auth-service:8081"
  EVENT_SERVICE_URL: "http://event-service:8082"